name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          Hi,

          Thank you for opening an issue! We appreciate you taking the time to report this and help us improve [Project Name]. Our team will investigate the problem and work on a resolution as soon as possible.

          Please provide any additional information that might help us reproduce and fix the issue, such as:
          - Steps to reproduce the issue
          - Expected and actual results
          - Screenshots or error messages
          - Your environment details (e.g., OS, browser, version of the software)

          We will keep you updated on the progress and notify you once the issue has been resolved.

          Best regards,  
          EXE Team
        pr-message: |
          Hi,

          Thank you for your pull request! We appreciate your contribution to our project. Our team will review your changes as soon as possible. If we need any additional information or modifications, we will let you know.

          In the meantime, please ensure that:
          - All tests are passing
          - Your code follows our coding standards
          - The documentation is updated, if necessary

          Thank you for helping us improve [Project Name]!

          Best regards,  
          EXE Team
